# This is a basic workflow to help you get started with Actions

name: vmss-flex-cassandra-demo

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
    paths:
      - 'vmss-flex-n-tier-demo/**'
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      AZURE_RG: 'vmss-flex-cassandra-demo'
      AZURE_LOCATION: 'southcentralus'
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Login to Azure using service principle
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep File to Azure via Azure CLI Action
        uses: Azure/cli@1.0.4
        with:
          # Specify the script here
          inlineScript: |
            az deployment sub create -n $AZURE_RG -l $AZURE_LOCATION -f $GITHUB_WORKSPACE/vmss-flex-n-tier-demo/main.bicep
          # Azure CLI version to be used to execute the script. If not provided, latest version is used
          # azcliversion: # optional, default is latest
